openapi: 3.0.1
info:
  title: Orders API
  description: Orders Microservice
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/orders/createOrder:
    post:
      tags:
      - orders-controller
      operationId: saveOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int32
  /api/orders/retriveOrders:
    get:
      tags:
      - orders-controller
      operationId: retrieveAllOrders
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
  /api/orders/fetchResponseData:
    get:
      tags:
      - orders-controller
      operationId: fetchResponseData
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataResponse'
components:
  schemas:
    Order:
      type: object
      properties:
        orderNumber:
          type: integer
          format: int32
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        productID:
          type: integer
          format: int32
    DataResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
